You should be using the Catch2 Macros that contain `THROWS` in their name.  
These allow you to check specific things about exceptions during testing.
The following is a comprehensive showcase of how these macros could have been used.

```cpp
TEST_CASE("check that .at throws exception for bad index access") {
    auto states = xector{"california", "texas", "florida", "new mexico"};

    SECTION("check that poor access throws error") {
        CHECK_THROWS(states.at(2));
    }

    SECTION("verify that a std::out_of_range is thrown") {
        CHECK_THROWS_AS(states.at(2), std::out_of_range);
    }

    SECTION("confirm error message") {
        CHECK_THROWS_WITH(states.at(2), "index 2 is out of range for an xector of size 2");
    }
}
```

It is best to build up the tests in order of complexity.  
To address coverage, finish once all aspects of the exception have been covered i.e.:

- that an exception is thrown;
- it produces the right error message;
- its exception type is correct.

Once you have tested each granular aspect of the exception, you can use the `CHECK_THROWS_MATCHES` macro to check for the exception message and type at once.

```cpp
TEST_CASE("check that .at throws exception for bad index access") {
    auto states = xector{"california", "texas", "florida", "new mexico"};

    CHECK_THROWS_MATCHES(states.at(2), std::out_of_range, Catch::Matchers::Message("index 2 is out of range for an xector of size 2"));
}
```

You can read more about it in the [Catch2 documentation](https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md).
